# Generated by Django 4.2.23 on 2025-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0002_users_email_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default='bsse23027@itu.edu.pk', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='1244355', max_length=20, null=True),
        ),
    ]
