# Generated by Django 5.1.3 on 2025-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloWorld", "0004_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
