# Generated by Django 5.1.3 on 2025-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloWorld", "0006_alter_users_email_alter_users_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="helloWorld.users"
            ),
        ),
    ]
