# Generated by Django 5.1.3 on 2025-08-11 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloWorld", "0007_users_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
