# Generated by Django 5.1.3 on 2025-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloWorld", "0008_images_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
